//Current User
export const GET_CURRENTUSER = 'GET_CURRENTUSER';
export const LOGOUT_CURRENTUSER = 'LOGOUT_CURRENTUSER';

//Categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const SAVE_CURRENT_CATEGORY = 'SAVE_CURRENT_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';

//sent
export const GET_SENT_TRANSACTIONS = 'GET_SENT_TRANSACTIONS';

//contacts
export const GET_CONTACTS = 'GET_CONTACTS';
